// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Contextos;

namespace Persistence.Migrations
{
    [DbContext(typeof(NSysPDbContext))]
    [Migration("20220227000720_ActualizacionFechaModificacion4")]
    partial class ActualizacionFechaModificacion4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.PedidoDet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Id Consecutivo del pedido")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cantidad")
                        .HasColumnType("float")
                        .HasComment("Cantidad solicitada");

                    b.Property<bool>("EsCadaUno")
                        .HasColumnType("bit")
                        .HasComment("Si el precio es por unidad y no por caja");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength(true)
                        .HasComment("Estatus del articulo del Pedidio");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified))
                        .HasComment("Fecha de Creacion");

                    b.Property<DateTime>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified))
                        .HasComment("Fecha de Creacion");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasComment("El id del Cliente");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int")
                        .HasComment("El id del Empleado");

                    b.Property<int>("IdMarca")
                        .HasColumnType("int")
                        .HasComment("Id del Catalogo de Marcas");

                    b.Property<int>("IdProdMaestro")
                        .HasColumnType("int")
                        .HasComment("Id del catalogo de ProdMaestro");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasComment("Notas para el que va a surtir el reglon del Pedido");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdCliente" }, "IXFK_PedidoDet_Cliente");

                    b.HasIndex(new[] { "IdEmpleado" }, "IXFK_PedidoDet_Empleado");

                    b.HasIndex(new[] { "IdMarca" }, "IXFK_PedidoDet_Marca");

                    b.HasIndex(new[] { "IdProdMaestro" }, "IXFK_PedidoDet_ProdMaestro");

                    b.HasIndex(new[] { "IdCliente", "IdProdMaestro", "IdMarca", "Estatus" }, "IX_NoDuplicado")
                        .IsUnique();

                    b.ToTable("PedidoDet");

                    b
                        .HasComment("Listado de Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
